services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
      - ./backend/uploads:/app/uploads
      - ./backups:/app/backups
    environment:
      - DATABASE_URL=sqlite:///./data/pats.db
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--openssl-legacy-provider
      - VITE_DEV_SERVER_HOST=0.0.0.0
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend 