"""Initial migration

Revision ID: 041bd0560732
Revises: 
Create Date: 2025-07-09 10:02:03.905478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '041bd0560732'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=False)
    op.add_column('applications', sa.Column('resume_filename', sa.String(), nullable=False))
    op.add_column('applications', sa.Column('resume_file_path', sa.String(), nullable=False))
    op.add_column('applications', sa.Column('cover_letter_filename', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('cover_letter_file_path', sa.String(), nullable=True))
    op.create_index('idx_company_status', 'applications', ['company_name', 'status'], unique=False)
    op.create_index('idx_source_status', 'applications', ['source', 'status'], unique=False)
    op.create_index('idx_status_date', 'applications', ['status', 'date_applied'], unique=False)
    op.create_index(op.f('ix_applications_created_at'), 'applications', ['created_at'], unique=False)
    op.create_index(op.f('ix_applications_date_applied'), 'applications', ['date_applied'], unique=False)
    op.create_index(op.f('ix_applications_source'), 'applications', ['source'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_unique_constraint(None, 'applications', ['job_id'])
    op.drop_column('applications', 'resume_version')
    op.add_column('contacts', sa.Column('linkedin_url', sa.String(), nullable=True))
    op.create_index('idx_company_type', 'contacts', ['company', 'contact_type'], unique=False)
    op.create_index('idx_name_company', 'contacts', ['name', 'company'], unique=False)
    op.create_index(op.f('ix_contacts_contact_type'), 'contacts', ['contact_type'], unique=False)
    op.create_index(op.f('ix_contacts_created_at'), 'contacts', ['created_at'], unique=False)
    op.create_index(op.f('ix_contacts_name'), 'contacts', ['name'], unique=False)
    op.create_index('idx_contact_date', 'interactions', ['contact_id', 'date'], unique=False)
    op.create_index('idx_type_date', 'interactions', ['interaction_type', 'date'], unique=False)
    op.create_index(op.f('ix_interactions_contact_id'), 'interactions', ['contact_id'], unique=False)
    op.create_index(op.f('ix_interactions_date'), 'interactions', ['date'], unique=False)
    op.create_index(op.f('ix_interactions_interaction_type'), 'interactions', ['interaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interactions_interaction_type'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_date'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_contact_id'), table_name='interactions')
    op.drop_index('idx_type_date', table_name='interactions')
    op.drop_index('idx_contact_date', table_name='interactions')
    op.drop_index(op.f('ix_contacts_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_created_at'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_contact_type'), table_name='contacts')
    op.drop_index('idx_name_company', table_name='contacts')
    op.drop_index('idx_company_type', table_name='contacts')
    op.drop_column('contacts', 'linkedin_url')
    op.add_column('applications', sa.Column('resume_version', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'applications', type_='unique')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_source'), table_name='applications')
    op.drop_index(op.f('ix_applications_date_applied'), table_name='applications')
    op.drop_index(op.f('ix_applications_created_at'), table_name='applications')
    op.drop_index('idx_status_date', table_name='applications')
    op.drop_index('idx_source_status', table_name='applications')
    op.drop_index('idx_company_status', table_name='applications')
    op.drop_column('applications', 'cover_letter_file_path')
    op.drop_column('applications', 'cover_letter_filename')
    op.drop_column('applications', 'resume_file_path')
    op.drop_column('applications', 'resume_filename')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_table('settings')
    op.drop_table('profile')
    # ### end Alembic commands ###
